name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: ${{ https://gist.github.com/SeoYeonBae/b5764d293ac75addfca2e606a09e1919 }}
          TIMEZONE: Asia/Seoul
